# Numpy Assignment :

# 1.Create a 3x3x3 array with random values

In [7]:
# random values of integer types
import numpy as np

x = np.random.randint(1,100,(3,3,3))
print(x)

[[[ 7 19 87]
  [85 92 96]
  [35 10 23]]

 [[57 51 81]
  [13 87 41]
  [98 65 82]]

 [[91 71 79]
  [88 14 50]
  [92 70 88]]]


In [97]:
# in float

import numpy as np

x = np.random.random((3,3,3))

print(x)

[[[0.31781654 0.43922328 0.98520063]
  [0.49536158 0.4779798  0.33781956]
  [0.97208758 0.52301483 0.15688033]]

 [[0.84684868 0.63606829 0.15746345]
  [0.13331504 0.38037933 0.46047921]
  [0.59379509 0.85235726 0.1891608 ]]

 [[0.939698   0.45742859 0.83653136]
  [0.94128284 0.49827069 0.6616531 ]
  [0.66110386 0.86024691 0.82096555]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [34]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Define the values to be placed just below the diagonal
values = np.array([1, 2, 3, 4])

# Fill the values just below the diagonal
for i in range(1, 5):
    matrix[i, i-1] = values[i-1]

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.ones((8, 8), dtype=int)

# Use slicing to set alternating elements to 1
matrix[1::2, ::2] = 0  # Odd rows, even columns
matrix[::2, 1::2] = 0  # Even rows, odd columns

print("Checkerboard pattern:")

# Print the checkerboard pattern matrix
print(matrix)


Checkerboard pattern:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4.Normalize a 5x5 random matrix

In [50]:
import numpy as np

# Generate a random 5x5 matrix with values between 0 and 1
random_matrix = np.random.randint(1,10,(5, 5))

# Calculate the mean and standard deviation of the matrix
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[8 3 6 4 3]
 [6 6 2 5 8]
 [5 9 1 7 3]
 [6 2 6 8 7]
 [2 9 3 4 3]]

Normalized Matrix:
[[ 1.26463396 -0.87157206  0.41015156 -0.44433085 -0.87157206]
 [ 0.41015156  0.41015156 -1.29881326 -0.01708965  1.26463396]
 [-0.01708965  1.69187517 -1.72605447  0.83739276 -0.87157206]
 [ 0.41015156 -1.29881326  0.41015156  1.26463396  0.83739276]
 [-1.29881326  1.69187517 -0.87157206 -0.44433085 -0.87157206]]


# 5.How to find common values between two arrays?

In [54]:
import numpy as np


array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values using NumPy's intersect1d function
common_values = np.intersect1d(array1, array2)
print('Array1 is: ',array1)
print('Array2 is: ',array2)

print("Common values in between these two arrays:", common_values)


Array1 is:  [1 2 3 4 5]
Array2 is:  [3 4 5 6 7]
Common values in between these two arrays: [3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [61]:
from datetime import datetime, timedelta

# Get the current date
today = datetime.now()

# Calculate the date for yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime("%d/%m/%Y")
yesterday_str = yesterday.strftime("%d/%m/%Y")
tomorrow_str = tomorrow.strftime("%d/%m/%Y")

# Print the dates
print("Yesterday Date Is:", yesterday_str)
print("Today Date Is    :", today_str)
print("Tomorrow Date Is :", tomorrow_str)


Yesterday Date Is: 20/09/2023
Today Date Is    : 21/09/2023
Tomorrow Date Is : 22/09/2023


# 7.Consider two random array A and B, check if they are equal.

In [66]:
import numpy as np

# Create two random arrays A and B
array1 = np.random.randint(0, 5, (3, 3))  # Create a 3x3 random integer array with values between 0 and 4
array2 = np.random.randint(0, 5, (3, 3))  # Create another 3x3 random integer array

print('Array1 is:\n', array1)
print('Array2 is:\n', array2)

# Check if arrays A and B are equal
are_equal = np.array_equal(array1, array2)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Array1 is:
 [[0 1 1]
 [2 0 0]
 [3 4 3]]
Array2 is:
 [[0 0 4]
 [4 2 4]
 [0 2 1]]
Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [81]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0: \n")
print(random_vector)


Random vector with the maximum value replaced by 0 

[0.85156365 0.79962968 0.23520586 0.90383269 0.19826679 0.
 0.20576717 0.30855369 0.55339218 0.59064583]


# 9.How to print all the values of an array?

In [8]:
import numpy as np

# Take the number of elements as input
try:
    num_elements = int(input("Enter the number of elements: "))
except ValueError:
    print("Invalid input. Please enter a valid integer.")
    exit()

# Initialize an empty list to store the input values
input_values = []

# Take user input for the array values line by line
for i in range(num_elements):
    value = input(f"Enter value {i + 1}/{num_elements}: ")
    input_values.append(value)

try:
    # Convert the input values to a NumPy array of float data type
    my_array = np.array(input_values, dtype=np.int32)
    
    # Print the values of the NumPy array
    print("Array values:")
    for element in my_array:
        print(element,end=" ")
except ValueError:
    print("Invalid input. Please enter valid numeric values.")


Enter the number of elements: 5
Enter value 1/5: 8
Enter value 2/5: 9
Enter value 3/5: 7
Enter value 4/5: 3
Enter value 5/5: 4
Array values:
8 9 7 3 4 

# 10.Subtract the mean of each row of a matrix

In [9]:
import numpy as np

# Create a sample matrix (replace this with your matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
result_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nResult Matrix (mean subtracted from each row):")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result Matrix (mean subtracted from each row):
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [50]:
import numpy as np

# Given vector
vector = np.ones(10)  # Initialize a vector with all elements as 1

# Indices vector (with repeated indices)
indices = np.random.randint(0,10, 15)  # Random indices (for illustration)

# Print the original vector
print("Original Vector:")
print(vector)

# Create a unique index array to avoid repetition
unique_indices = np.unique(indices)

# Print the unique indices
print("\nUnique Indices:")
print(unique_indices)

# Add 1 to each element at the unique indices
vector[unique_indices] += 1

# Print the final vector
print("\nFinal Vector:")
print(vector)


Original Vector:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Unique Indices:
[0 1 2 5 6 7 8 9]

Final Vector:
[2. 2. 2. 1. 1. 2. 2. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [59]:
import numpy as np

# Create two 2x2 matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Calculate the dot product
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal elements of the dot product
diagonal = np.diag(dot_product)

print("Matrix1:")
print(matrix1)

print("\nMatrix2:")
print(matrix2)

print("\nDot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)


Matrix1:
[[1 2]
 [3 4]]

Matrix2:
[[5 6]
 [7 8]]

Dot Product:
[[19 22]
 [43 50]]

Diagonal of Dot Product:
[19 50]


# 13.How to find the most frequent value in an array?

In [65]:
import numpy as np

# Generate an array of 50 random integers between 0 and 9
Z = np.random.randint(0, 10, 20)

# Print the generated array
print(Z)

# Use bincount to count occurrences of each integer and find the most frequent one
most_frequent = np.bincount(Z).argmax()

# Print the rank (most frequent integer)
print('rank:', most_frequent)


[3 9 7 2 8 7 7 8 4 0 4 3 0 0 7 1 4 5 5 2]
rank: 7


# 14.How to get the n largest values of an array

In [67]:
import numpy as np

# Take user input for n
n = int(input("Enter the value of n: "))

# Generate a random array of integers (you can specify the size)
array_size = 20  # Adjust this as needed
my_array = np.random.randint(1, 100, array_size)  # Generates random integers between 1 and 99

# Use numpy.partition to get the n largest values
largest_n_values = np.partition(my_array, -n)[-n:]

print(f"The random array is:", my_array)
print(f"The {n} largest values in the array are:", largest_n_values)


Enter the value of n: 5
The random array is: [21 46 15 50 78 27 23 49 45 36 38 60 43 60 23 81 65 18 25 35]
The 5 largest values in the array are: [60 60 78 65 81]


# 15.How to create a record array from a regular array?

In [74]:
import numpy as np

# Create a regular array with data
regular_array = np.array([("Alice", 25), ("Bob", 30), ("Charlie", 22)])

# Define the structured data type (dtype) for the record array with separate types for each field
dtype = [('name', 'U10'), ('age', int)]

# Create an empty record array with the specified dtype
record_array = np.empty(len(regular_array), dtype=dtype)

# Assign values from the regular array to the record array
record_array['name'] = regular_array[:, 0]
record_array['age'] = regular_array[:, 1]

# Print the record array
print(record_array)



[('Alice', 25) ('Bob', 30) ('Charlie', 22)]


# 16.How to swap two rows of an array?

In [89]:
A = np.random.randint(1,5,(3,3))
print ('Original Array is :\n',A)

A[[0,2]] = A[[2,0]]

print ('After Swap Array is :\n',A)


Original Array is :
 [[1 4 4]
 [4 2 1]
 [1 1 4]]
After Swap Array is :
 [[1 1 4]
 [4 2 1]
 [1 4 4]]


# 17.Write python code to reshape to the next dimension of numpy array?


In [96]:
import numpy as np

# Create a 1D array (vector)
arr = np.random.randint(1, 10, 5)

# Reshape the array to the next dimension (2D)
reshaped_arr = arr.reshape((arr.shape[0]), 1)

print("Original Array:")
print(arr)
print("Original Array dimension:",arr.ndim)

print("Reshaped Array:")
print(reshaped_arr)
print("Reshaped Array dimension:",reshaped_arr.ndim)


Original Array:
[6 2 4 5 2]
Original Array dimension: 1
Reshaped Array:
[[6]
 [2]
 [4]
 [5]
 [2]]
Reshaped Array dimension: 2
